name: config.h

on:
  pull_request:
    paths:
      - "core/include/lplplugin/config.h"
      - ".github/workflows/config-header.yml"
  push:
    branches: [main]
    paths:
      - "core/include/lplplugin/config.h"
      - ".github/workflows/config-header.yml"

permissions:
  contents: read

jobs:
  template:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: MasterLaplace/.github/actions/check-config-header@466d7966bdc25daefb62faeda3e37bd954690c91 # ci/55-check-config-header-action
        with:
          config-header: core/include/lplplugin/config.h
          prefix: LPLPLUGIN
