name: config.h

on:
  pull_request:
    paths:
      - "core/include/lplplugin/config.h"
      - ".github/workflows/config-header.yml"
  push:
    branches: [main]
    paths:
      - "core/include/lplplugin/config.h"
      - ".github/workflows/config-header.yml"

permissions:
  contents: read

jobs:
  template:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: MasterLaplace/.github/actions/check-config-header@556efbe3ed40c4b0e36d87dc42fe8412b93945a1 # main
        with:
          config-header: core/include/lplplugin/config.h
          prefix: LPLPLUGIN
